# Use Ubuntu as base image
FROM ubuntu:22.04

# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Set Python environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create symbolic links for python commands
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# Install PostgreSQL development package and gcc
RUN apt-get update && apt-get install -y postgresql-server-dev-all gcc

# Set the working directory
WORKDIR /ms_embedding_documents

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the .env file
COPY .env .

# Copy application files
COPY . .

# Expose API port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]