# Use Ubuntu as base image
FROM ubuntu:22.04

# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Set Python environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Create symbolic links for python commands
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# Set the working directory
WORKDIR /front_end_streamlit

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the .env file
COPY .env .

# Copy application files
COPY . .

# Expose API port
EXPOSE 8501

# Run the application
CMD ["streamlit", "run", "app/main.py"]